[package]
name = "rocket-client-addr"
version = "0.3.2"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-client-addr"
homepage = "https://magiclen.org/rocket-client-addr"
keywords = ["rocket", "server", "web", "ip", "http"]
categories = ["parser-implementations"]
description= "This crate provides a request guard used for getting an IP address from a client."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/rocket-client-addr", branch = "master" }

[dependencies]
rocket = "0.4"